mysqldb:
  image: mysql:latest
  environment:
    MYSQL_DATABASE: cms
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql
    MYSQL_ROOT_PASSWORD: supersecret
  volumes:
    - /srv/docker/mysql/data/db:/var/lib/mysql
  labels:
    org.javatraining.cms.version: "test"
mywildfly:
  dockerfile: Dockerfile-wildfly
  build: .
  links:
    - mysqldb:db
  ports:
    - "{{WILDFLY_IP}}:{{WILDFLY_PORT}}:8080"
    - "{{WILDFLY_IP}}:{{SMTP_PORT}}:{{SMTP_PORT}}"
  labels:
    org.javatraining.cms.version: "test"


