postgresql:
  image: sameersbn/postgresql:9.4-2
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql
gitlab:
  image: sameersbn/gitlab:7.13.2
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "{{GITLAB_IP}}:{{GITLAB_PORT}}:80"
  environment:
    - TZ=Europe/Kiev
    - SMTP_ENABLED=true
    - SMTP_HOST={{SMTP_HOST}}
    - SMTP_PORT={{SMTP_PORT}}
    - SMTP_USER={{SMTP_ADDRESS}}
    - SMTP_PASS={{SMTP_PASSWORD}}
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login
    - GITLAB_TIMEZONE=Kyiv
    - GITLAB_HOST={{GITLAB_IP}}
    - GITLAB_PORT={{GITLAB_PORT}}
    - GITLAB_EMAIL={{GITLAB_ROOT_EMAIL}}
    - GITLAB_EMAIL_REPLY_TO={{GITLAB_ROOT_EMAIL}}
    - GITLAB_EMAIL_DISPLAY_NAME=JavaTraining-Gitlab
    - GITLAB_ROOT_PASSWORD={{GITLAB_ROOT_PASSWORD}}
    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
redis:
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis