/**
 * Created by olga on 25.06.15.
 */
function CourseContentCtrl($scope, lectures, course, CourseContentService) {
    $scope.lectures = lectures;
    $scope.hidePractices = false;
    $scope.editMode = false;

    $scope.removeLecture = function (lectureOrderNum) {

        $scope.autoGeneratedNewsLectureRemoved($scope.lecture);
        CourseContentService.removeLecture(course.id, lectureOrderNum).then(function (success) {
            if (success.responseStatus == 200) {
                CourseContentService.getLectures(course.id).then(function (lectures) {
                    if (lectures.responseStatus == 200) {
                        $scope.lectures = lectures;
                    }
                });
            }
        });
    };

    $scope.autoGeneratedNewsLectureRemoved = function (lecture) {
        $scope.news.date = new Date();
        $scope.news.courseId = $stateParams.courseId;
        $scope.news.title = "Лекция по курсу " + course.name
            + " была удалена";
        $scope.news.content = "Тема лекции: " + lecture.topic;
        NewsService.updateNews($scope.news);
    };
}